### ISSUE TITLE
Crear guía de Interfaz de Usuario

### ISSUE THREAD

**Issue by mendozagioo** [CodeandoMexico/tu-plataforma-abierta#19]
Creo que es importante crear una guía de Interfaz de Usuario para que cada contribuidor que participe en el proyecto sepa que lineamientos de diseño se deben de seguir para crear vistas nuevas o agregar nuevas características a vistas ya creadas, así cada contribución será menos suseptible a mejoras de diseño y el proyecto avanzará más rápido.
Yo estoy trabajando en ésta guía, y si alguien más está interesado en participar conmigo en este issue, porfavor ponganse en contacto conmigo para aportar sus ideas.

**Comment by mendozagioo** [comment]
Guía creada (aún en proceso, pero ya están los elementos más usados)
https://github.com/CodeandoMexico/tu-plataforma-abierta/wiki/Gu%C3%ADa-UI

**Comment by miguelsalazar** [comment]
LGTM.
